In [2]:
# 导入numpy
import numpy as np

In [3]:
# 创建数组
t1 = np.array([1,2,3])
type(t1)

t2 = np.array([[1],[2]])
print(t2)
print("*"*117)

t3 = np.array([[[[1],[1,2],[1,2,3],[2,3,4],[3,4,5]]]])
print(t3)
print("*"*117)


t3 = np.array([[[[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8]]]])
print(t3)
print("*"*117)

numpy.ndarray

In [14]:
t1.dtype  # dtype('int64')

dtype('int64')

In [15]:
t1.size  # 元素的个数 3

3

In [17]:
t1.nbytes  # 总字节数24

24

In [18]:
t1.itemset

<function ndarray.itemset>

In [19]:
t1.itemsize  # 一个元素的长度

8

## 形状比较

In [31]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[2,5,6],[1,2,3],[3,5,6]]])

print(a)
a.shape # 1维形状 (4,)

[1 2 3 4]


(4,)

In [32]:
print(b)
b.shape  # 2维形状 (2,3)

[[1 2 3]
 [4 5 6]]


(2, 3)

In [34]:
print(c)
c.shape  # 3维形状 (2, 2, 3)

[[[1 2 3]
  [2 5 6]
  [1 2 3]
  [3 5 6]]]


(1, 4, 3)

In [29]:
b.flags
# 内存风格
# 默认C风格

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## numpy中的ndarray的属性

In [31]:
t1 = np.array([1,2,3])
# 获取数组的形状
t1.shape   # 1维数组

(3,)

In [33]:
# 获取数组的维度
print(t1.ndim)

1


In [12]:
t2 = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(t2.shape)
print(t2.ndim)   # 3维数组

(1, 4, 3)
3


In [15]:
# 获取数组中元素的个数
t2.size

12

In [24]:
#1.创建数组
t1 = np.array([1,2,3])
print(t1)
print(t1.ndim)
type(t1)
#获取数组的形状
t1.shape #1维
#获取数组的维度

[1 2 3]
1


(3,)

In [30]:
t2 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(t2.shape)
# print(t2.ndim)
#获取数组中元素的个数
# t2.size
t2.shape

(2, 2, 3)


(2, 2, 3)

## numpy三维数组的形状

In [40]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [53]:
# 生成一个数组
np.arange(24).reshape((2,3,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [9]:
b = np.arange(24).reshape((2,3,4))
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
np.arange(120).reshape((2,3,4,5))

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

## 获取ndarry中数据的类型

In [36]:
t1 = np.array([1,2,3])

In [37]:
t1

array([1, 2, 3])

In [38]:
t1.dtype

dtype('int64')

In [39]:
np.array([1,2,3],dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [40]:
np.array([1,0,1,0],dtype=np.bool)

array([ True, False,  True, False])

In [41]:
np.array([1,0,1,0],dtype=float)

array([1., 0., 1., 0.])

In [43]:
# 转换数据类型的方法
t1.astype(np.float32)

array([1., 2., 3.], dtype=float32)

In [44]:
t1.astype(np.float128)

array([1., 2., 3.], dtype=float128)