## 1、0和1的数组

In [1]:
import numpy as np

- empty(shape[, dtype, order])
- empty_like(a[, dtype, order, subok])
- eye(N[, M, k, dtype, order])
- identity(n[, dtype])
- ones(shape[, dtype, order])
- ones_like(a[, dtype, order, subok])
- zeros(shape[, dtype, order])
- zeros_like(a[, dtype, order, subok])
- full(shape, fill_value[, dtype, order])
- full_like(a, fill_value[, dtype, order, subok])

In [7]:
zero = np.zeros([3,4])   # 创建3行4列的全为0的数组
# print(zero)
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2、从现有的数据中创建


- array(object[, dtype, copy, order, subok, ndmin])

- asarray(a[, dtype, order])

- copy(a[, order])


In [9]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 从现有的数组当中创建
a1 = np.array(a)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# 相当于索引的形式，并没有真正的创建一个新的
a2 = np.asarray(a)
a2

array([[1, 2, 3],
       [4, 5, 6]])

## 2.1、关于array和asarray的不同

In [26]:
data = np.ones((3,4))  # 创建3行4列的全为1的数组
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
data1 = np.array(data)  # 使用array的方式创建data1
# data1

In [28]:
data2 = np.asarray(data)  # 使用asarray的方式创建data2
data2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
data[1,1] = 10  # 修改data中第2行第2列位置的4为10

In [30]:
data

array([[ 1.,  1.,  1.,  1.],
       [ 1., 10.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [37]:
data1 = np.array(data)  # 使用array的方式创建data1
data1

array([[ 1.,  1.,  1.,  1.],
       [ 1., 10.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [38]:
data2 = np.asarray(data)  # 使用asarray的方式创建data2
data2

array([[ 1.,  1.,  1.,  1.],
       [ 1., 10.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

## 3、创建固定范围的数组

- np.linspace (start, stop, num, endpoint, retstep, dtype)
生成等间隔的序列
```
start 序列的起始值
stop 序列的终止值，
如果endpoint为true，该值包含于序列中
num 要生成的等间隔样例数量，默认为50
endpoint 序列中是否包含stop值，默认为ture
retstep 如果为true，返回样例，
以及连续数字之间的步长
dtype 输出ndarray的数据类型
```

In [40]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

其它的还有:

- 创建一个数组，从start到stop，step为步长 ，类似python的arange函数
    - numpy.arange(start,stop, step, dtype)
    - numpy.arange(10, 50, 2)
- 创建等比数组，从指数从start到stop，默认包含stop，num表示数组中的个数，base表示底数，默认是10，endpoint默认为True，表示默认包含stop
    - numpy.logspace(start,stop, num, endpoint, base, dtype)
    - numpy.logspace(0,9,10)
    - numpy.logspace(0,9,10,base=2)

In [42]:
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

## 4、创建随机数组

- np.random模块
    - 均匀分布
        - np.random.rand(10) :返回长度为10的数组，其中的元素取值为0-1
        - np.random.uniform(0,100) ：返回一个数，取值为0-100
        - np.random.randint(100) ：返回一个整数，取值范围0-100
- 正态分布
    - 给定均值／标准差／维度的正态分布
    - np.random.normal(1.75, 0.2, (3,4))
    - np.random.standard_normal(size=(3,4))


In [43]:
# 创建均匀分布的数组
# 0~1
np.random.rand(10)

array([0.78172339, 0.88272682, 0.05684336, 0.62146769, 0.78940244,
       0.97650439, 0.33833186, 0.41717912, 0.10531266, 0.73890331])

In [46]:
# 默认范围一个数
np.random.uniform(0,100)

57.915010906439335

In [48]:
# 随机整数
np.random.randint(10)

5

In [49]:
# 创建均值为1.75，标准差为0.1，形状为（10，10）的数组
np.random.normal(1.75,0.1,(10,10))

array([[1.79384747, 1.74694415, 1.73443504, 1.64662125, 1.89674341,
        1.71097878, 1.8792533 , 1.70912562, 1.66402618, 1.75735235],
       [1.84852347, 1.8138473 , 1.6480348 , 1.71974501, 1.91397599,
        1.58830162, 1.61635641, 1.51733628, 1.85913492, 1.80673445],
       [1.64045226, 1.77643334, 1.80833862, 1.62579987, 1.75844724,
        1.67475067, 1.71437346, 1.80509686, 1.80422966, 1.8121552 ],
       [1.78314521, 1.68840477, 1.81088063, 1.85458444, 1.5611888 ,
        1.75864511, 1.6789177 , 1.86361256, 1.57586361, 1.79602968],
       [1.90234776, 1.59999696, 1.82040762, 1.80093176, 1.91753429,
        1.67508953, 1.76621459, 1.60542134, 1.68365735, 1.73025023],
       [1.64372167, 1.73919639, 1.61577494, 1.83201258, 1.67312383,
        1.7644288 , 1.79942969, 1.74172147, 1.69262969, 1.78772534],
       [1.7566237 , 1.75797292, 1.67303591, 1.81627157, 1.85465899,
        1.75795785, 1.73373755, 1.76467977, 1.74454759, 1.75102719],
       [1.78245647, 1.73513786, 1.5911069