In [2]:
import numpy as np

In [7]:
data = np.random.standard_normal((500,505))

In [8]:
data

array([[ 1.51702684, -0.98584015, -0.92617438, ...,  0.12543871,
        -0.88037443,  0.42651363],
       [ 0.22101952, -0.46380865, -0.4075636 , ...,  0.69151547,
         0.72246626,  2.7114523 ],
       [ 0.07481116,  1.02651672, -1.40129477, ..., -1.2073459 ,
        -1.00861813,  0.17020551],
       ...,
       [ 0.66339867,  1.73457574, -0.89020499, ...,  1.77051914,
        -0.52127032, -0.63632232],
       [-0.69178794, -0.44454996,  0.30480946, ..., -0.13566079,
         0.03554434,  0.01343969],
       [ 1.46250839, -0.02875206, -0.39543216, ..., -0.66388343,
        -0.03138109, -0.37512223]])

In [9]:
data > 0.5  # data中的每一个值和0.5进行判断

array([[ True, False, False, ..., False, False, False],
       [False, False, False, ...,  True,  True,  True],
       [False,  True, False, ..., False, False, False],
       ...,
       [ True,  True, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False]])

In [10]:
# bool索引，返回索引中为true的位置的值
temp = data[:4,:4].copy()  # data[:起始，:结束]
temp

array([[ 1.51702684, -0.98584015, -0.92617438,  0.40726845],
       [ 0.22101952, -0.46380865, -0.4075636 ,  0.33333132],
       [ 0.07481116,  1.02651672, -1.40129477,  0.02148039],
       [-0.44018195,  1.77667584,  1.129655  ,  1.06563153]])

In [19]:
temp[temp>0.2]

array([1.51702684, 0.40726845, 0.22101952, 0.33333132, 1.02651672,
       1.77667584, 1.129655  , 1.06563153])

In [20]:
temp[temp>0.5]

array([1.51702684, 1.02651672, 1.77667584, 1.129655  , 1.06563153])

In [21]:
temp>-100

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
np.all(temp>-100)  # 判断temp>-100是否全部为true,如果是返回true

True

## 实现对数组的去重

In [24]:
np.unique([1,2,3,1,2,3])

array([1, 2, 3])

In [26]:
# 把temp中大于0的值转换为1，小于等于0的转换为0
np.where(temp>0,1,0)

array([[1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 0, 1],
       [0, 1, 1, 1]])

In [27]:
temp

array([[ 1.51702684, -0.98584015, -0.92617438,  0.40726845],
       [ 0.22101952, -0.46380865, -0.4075636 ,  0.33333132],
       [ 0.07481116,  1.02651672, -1.40129477,  0.02148039],
       [-0.44018195,  1.77667584,  1.129655  ,  1.06563153]])

In [28]:
# python中
a = 3
2<=a<=4

True

In [29]:
# 使用路基与现实更复杂的条件
np.logical_and(temp>0.5,temp<1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
# 使用逻辑或的操作
np.logical_or(temp<0,temp>1)

array([[ True,  True,  True, False],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [32]:
temp>0.5

array([[ True, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [33]:
temp<1

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True, False, False, False]])

## numpy中的统计方法的api

In [43]:
temp = data[:3,:3]

In [44]:
temp

array([[ 1.51702684, -0.98584015, -0.92617438],
       [ 0.22101952, -0.46380865, -0.4075636 ],
       [ 0.07481116,  1.02651672, -1.40129477]])

In [45]:
np.max(temp)

1.5170268373402287

In [46]:
# axis=0表示按照列（竖着方向）进行统计，把每一例对应位置（索引位置）的数据进行统计
np.max(temp,axis=0)  # 统计每列的最大值

array([ 1.51702684,  1.02651672, -0.4075636 ])

In [48]:
# axis=1表示按照行（一个列表代表一行）进行统计，把每一行对应位置（索引位置）的数据进行统计
np.max(temp,axis=1)  # 统计每行的最大值

array([1.51702684, 0.22101952, 1.02651672])

In [49]:
np.min(temp,axis=0)

array([ 0.07481116, -0.98584015, -1.40129477])

In [50]:
np.min(temp,axis=1)

array([-0.98584015, -0.46380865, -1.40129477])

In [51]:
# median  中位数
np.median(temp,axis=1)

array([-0.92617438, -0.4075636 ,  0.07481116])

In [52]:
# std平均数
np.std(temp,axis=1)

array([1.1660539 , 0.31042442, 0.99882713])

In [53]:
np.argmax(temp,axis=1)  # 横向获取所有数据中的最大值的位置

array([0, 0, 1])

In [55]:
np.argmax(temp,axis=0)  # 纵向获取所有数据中的最大值的位置

array([0, 2, 1])

In [56]:
np.argmin(temp,axis=1)  # 横向获取所有数据中的最小值的位置

array([1, 1, 2])

In [57]:
np.argmin(temp,axis=0)  # 纵向获取所有数据中的最小值的位置

array([2, 0, 2])