In [1]:
import numpy as np

In [4]:
t1 = np.arange(12)

In [5]:
t1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
t1 = np.arange(12).reshape((2,6))

In [7]:
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## 数组和数的计算

In [8]:
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
t1 + 1  # 每个数据都进行了 +1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
t1/2

array([[0. , 0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. , 5.5]])

In [12]:
t1 * 2

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22]])

## 数组和数组的计算

In [13]:
t2 = np.arange(10,22)
t2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [14]:
t2 = np.arange(10,22).reshape((2,6))

In [15]:
t2

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [16]:
t1 + t2  # 对应位置的数据进行计算

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [17]:
t1 * t2

array([[  0,  11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200, 231]])

In [18]:
t3 = np.array([[2,3,4]])

In [19]:
t3

array([[2, 3, 4]])

In [20]:
t1   

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
t1+t3   # 一维和二维不能运算

ValueError: operands could not be broadcast together with shapes (2,6) (1,3) 

In [22]:
t4 = np.array([[1],[2]])  # 二维

In [23]:
t4

array([[1],
       [2]])

In [24]:
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
t1+t4  # 能够相加，在行的方向进行相加

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13]])

In [26]:
t5 = np.array([[1,2,3,4,5,6]])
t5

array([[1, 2, 3, 4, 5, 6]])

In [27]:
t5 + t1  # 能够进行计算，在列的方向进行计算

array([[ 1,  3,  5,  7,  9, 11],
       [ 7,  9, 11, 13, 15, 17]])

## 矩阵的运算

In [28]:
t1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
t1_matrix = np.mat(t1)  # 将数组转换成矩阵类型

In [30]:
t1_matrix

matrix([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [31]:
type(t1_matrix)

numpy.matrix

In [32]:
# （8，2）*（2，1） = （8，1）
a = np.array([
    [80,86],
    [82,80],
    [85,78],
    [90,90],
    [86,82],
    [82,90],
    [78,80],
    [92,94]
])

In [34]:
b = np.array([
    [0.3],[0.7]
])

In [35]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [36]:
b

array([[0.3],
       [0.7]])

In [37]:
c = np.matmul(a,b)

In [38]:
c

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

## 数组的分割合并

In [39]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [40]:
c

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [41]:
np.concatenate([a,c],axis=1)  # 把数据作为列放在元数据的左右，和hstack的效果相同

array([[80. , 86. , 84.2],
       [82. , 80. , 80.6],
       [85. , 78. , 80.1],
       [90. , 90. , 90. ],
       [86. , 82. , 83.2],
       [82. , 90. , 87.6],
       [78. , 80. , 79.4],
       [92. , 94. , 93.4]])

In [46]:
d = c.reshape((4,2))
d

array([[84.2, 80.6],
       [80.1, 90. ],
       [83.2, 87.6],
       [79.4, 93.4]])

In [56]:
# 把数据作为列放在元数据的下面，和vstack的效果相同
np.concatenate([a,d],axis=0)  # 和vstack效果相同

array([[80. , 86. ],
       [82. , 80. ],
       [85. , 78. ],
       [90. , 90. ],
       [86. , 82. ],
       [82. , 90. ],
       [78. , 80. ],
       [92. , 94. ],
       [84.2, 80.6],
       [80.1, 90. ],
       [83.2, 87.6],
       [79.4, 93.4]])

In [51]:
print(a)

[[80 86]
 [82 80]
 [85 78]
 [90 90]
 [86 82]
 [82 90]
 [78 80]
 [92 94]]


In [52]:
print(b)

[[0.3]
 [0.7]]


In [53]:
print(d)

[[84.2 80.6]
 [80.1 90. ]
 [83.2 87.6]
 [79.4 93.4]]


In [55]:
# 把数据作为列放在元数据的下面
np.vstack([a,d])  # np.vstack() #竖直的方向进行操作

array([[80. , 86. ],
       [82. , 80. ],
       [85. , 78. ],
       [90. , 90. ],
       [86. , 82. ],
       [82. , 90. ],
       [78. , 80. ],
       [92. , 94. ],
       [84.2, 80.6],
       [80.1, 90. ],
       [83.2, 87.6],
       [79.4, 93.4]])

In [57]:
np.hstack([c,a])  # #np.hstack() #水平的方向进行操作

array([[84.2, 80. , 86. ],
       [80.6, 82. , 80. ],
       [80.1, 85. , 78. ],
       [90. , 90. , 90. ],
       [83.2, 86. , 82. ],
       [87.6, 82. , 90. ],
       [79.4, 78. , 80. ],
       [93.4, 92. , 94. ]])

## 数组的拼接

In [58]:
c

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [59]:
np.split(c,2)  # 等分，返回一个列表

[array([[84.2],
        [80.6],
        [80.1],
        [90. ]]), array([[83.2],
        [87.6],
        [79.4],
        [93.4]])]

In [60]:
np.split(c,3,axis=0)   # 不能等分 报错

ValueError: array split does not result in an equal division

In [63]:
np.split(c,4,axis=0)  # 等分

[array([[84.2],
        [80.6]]), array([[80.1],
        [90. ]]), array([[83.2],
        [87.6]]), array([[79.4],
        [93.4]])]