In [1]:
import numpy as np

In [5]:
t1 = np.array([1])
type(t1)

numpy.ndarray

In [31]:
t1 = np.array([1,2,3,4])
print(t1)
print("*"*117)

t2 = np.array([[1],[2]])
print(t2)
print("*"*117)

t3 = np.array([[[[1],[1,2],[1,2,3],[2,3,4],[3,4,5]]]])
print(t3)
print("*"*117)


t3 = np.array([[[[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8]]]])
print(t3)
print("*"*117)

[1 2 3 4]
*********************************************************************************************************************
[[1]
 [2]]
*********************************************************************************************************************
[[[list([1]) list([1, 2]) list([1, 2, 3]) list([2, 3, 4])
   list([3, 4, 5])]]]
*********************************************************************************************************************
[[[[1 2 3 4]
   [2 3 4 5]
   [3 4 5 6]
   [4 5 6 7]
   [5 6 7 8]]]]
*********************************************************************************************************************


In [33]:
t3.dtype

dtype('int64')

In [38]:
# t1.size
t3.size

20

In [40]:
t3.nbytes

160

In [41]:
t3.itemset

<function ndarray.itemset>

In [42]:
t3.itemsize

8

In [44]:
t3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [46]:
t3.shape

(1, 1, 5, 4)

In [48]:
t1.shape

(4,)

## numpy数组维度

In [63]:
t1 = np.array([1,2,3,4])
print(t1)
print(t1.ndim)
t1.shape   # 1维

[1 2 3 4]
1


(4,)

In [64]:
t2 = np.array([[1,2,3],[2,3,4]])
print(t2)
print(t2.ndim)
t2.shape  # 2维

[[1 2 3]
 [2 3 4]]
2


(2, 3)

In [65]:
t3 = np.array([[[1,2,3],[2,3,4],[3,4,5]]])
print(t3)
print(t3.ndim)
t3.shape  # 3维

[[[1 2 3]
  [2 3 4]
  [3 4 5]]]
3


(1, 3, 3)

## numpy三维数组的形状

In [68]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [82]:
# 生成一个数组
np.arange(24).reshape((2,3,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [83]:
b = np.arange(24).reshape((2,3,4))
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
